config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :reviews

  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def index
  @reviews = Review.all
end

def show
  @review = Review.find(params[:id])
end


def new

end


def create
  @review = Review.new(review_params)

  @review.save
  redirect_to @review
end

private
  def review_params
    params.require(:review).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1>All Reviews</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>

<%= link_to 'Back', reviews_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Review page', controller: 'reviews' %>